debugMessage: yes
# Default values for sharecrows-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

## current b/c rate limit from letsencrypt:
ingress:
  enabled: false
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/tls-acme: "true"

# serviceName, nodeport info
service:
  name: sharecrows-api
  type: NodePort
  externalPort: 80
  # internal port is inherited from nginx.internalPort

# nginx details. make sure to set proxy pass to api internalPort & listen port  via env & sed injection
nginx:
  repository: gcr.io/glassy-courage-146901/sharecrows-api-proxy
  tag: 9f19c6b80fea
  pullPolicy: IfNotPresent
  internalPort: 80
  resources:
    limits:
      cpu: 50m
      memory: 512Mi
    requests:
      cpu: 12m
      memory: 256Mi

# app details
api:
  repository: gcr.io/glassy-courage-146901/sharecrows-api
  tag: 5a287837727f
  pullPolicy: IfNotPresent
  internalPort: 8080
  configs:
    secretPath: /etc/beacon-api/configs
    # creationPath points to the decoded config dir locally (appended w/ `/*`), which is parsed & turned into a k8s secret
    creationPath: "conf/*"
  resources:
    limits:
      cpu: 100m
      memory: 2Gi
    requests:
      cpu: 25m
      memory: 1Gi

# cassandra serviceName
cassandra:
  serviceName: cass-cassandra.cassandra
