# Default values for sharecrows-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

## current b/c rate limit from letsencrypt:
ingress:
  enabled: false
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/tls-acme: "true"

# serviceName, nodeport info
service:
  name: sharecrows-api
  type: NodePort
  externalPort: 80
  # internal port is inherited from nginx.internalPort

# nginx details. make sure to set proxy pass to api internalPort & listen port  via env & sed injection
nginx:
  repository: <TBD>
  tag: <TBD>
  pullPolicy: <TBD>
  internalPort: <TBD>
  resources:
    limits:
      cpu: 50m
      memory: 512Mi
    requests:
      cpu: 12m
      memory: 256Mi

# app details
api:
  repository: <TBD>
  tag: <TBD>
  pullPolicy: <TBD>
  internalPort: <TBD>
  resources:
    limits:
      cpu: 100m
      memory: 1Gi
    requests:
      cpu: 25m
      memory: 2Gi

# cassandra serviceName
cassandra:
  serviceName: cass-cassandra.cassandra.svc.local.cluster
