// populate some data

use bkn;
INSERT INTO beacons (user_id, beacon_name, deploy_name) VALUES (6ba7b810-9dad-11d1-80b4-00c04fd430c8, 'a2', null);
INSERT INTO beacons (user_id, beacon_name, deploy_name) VALUES (6ba7b810-9dad-11d1-80b4-00c04fd430c8, 'a3', null);
INSERT INTO beacons (user_id, beacon_name, deploy_name) VALUES (6ba7b810-9dad-11d1-80b4-00c04fd430c8, 'a4', 'dep1');
INSERT INTO beacons (user_id, beacon_name, deploy_name) VALUES (6ba7b810-9dad-11d1-80b4-00c04fd430c8, 'a5', 'dep1');
INSERT INTO beacons (user_id, beacon_name, deploy_name) VALUES (6ba7b810-9dad-11d1-80b4-00c04fd430c8, 'a6', 'dep1');
INSERT INTO beacons (user_id, beacon_name, deploy_name) VALUES (6ba7b810-9dad-11d1-80b4-00c04fd430c8, 'a7', 'dep1');
INSERT INTO beacons (user_id, beacon_name, deploy_name) VALUES (6ba7b810-9dad-11d1-80b4-00c04fd430c8, 'a8', 'dep2');
INSERT INTO beacons (user_id, beacon_name, deploy_name) VALUES (6ba7b810-9dad-11d1-80b4-00c04fd430c8, 'a9', 'dep2');
INSERT INTO beacons (user_id, beacon_name, deploy_name) VALUES (6ba7b810-9dad-11d1-80b4-00c04fd430c8, 'a10', 'dep2');
INSERT INTO beacons (user_id, beacon_name, deploy_name) VALUES (6ba7b810-9dad-11d1-80b4-00c04fd430c8, 'a11', 'dep2');
INSERT INTO beacons (user_id, beacon_name, deploy_name) VALUES (6ba7b810-9dad-11d1-80b4-00c04fd430c8, 'a12', 'dep3');
INSERT INTO beacons (user_id, beacon_name, deploy_name) VALUES (6ba7b810-9dad-11d1-80b4-00c04fd430c8, 'a13', 'dep3');
INSERT INTO beacons (user_id, beacon_name, deploy_name) VALUES (6ba7b810-9dad-11d1-80b4-00c04fd430c8, 'a14', 'dep3');

